## Iris Dataset Overview:
The Iris dataset is a widely used dataset in machine learning and statistics, which is often used for demonstrating classification algorithms. It's a simple dataset with relatively small size and has been a standard benchmark in the machine learning community for testing various algorithms. The dataset consists of measurements for 150 Iris flowers across 3 different species: Iris setosa, Iris versicolor, and Iris virginica.

### Features of the Iris Dataset:
* Number of Samples: 150
* Number of Features: 4 (Sepal Length, Sepal Width, Petal Length, Petal Width)
* Target Classes: 3 species of Iris flowers (Setosa, Versicolor, Virginica)
* Class Distribution: Each class contains 50 samples

### Import Required Libraries

In [ ]:
# Import necessary libraries for data manipulation, model training, and evaluation
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
from sklearn.datasets import load_iris

### Load and Explore the Dataset

In [ ]:
# Load Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Check the shape and preview the dataset
print("Features:", iris.feature_names)
print("Target:", iris.target_names)

Features: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target: ['setosa' 'versicolor' 'virginica']


### Data Preprocessing

In [ ]:
# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Model Training and Evaluation

In [ ]:
# Train the Random Forest model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Predict the target values for the test set
y_pred = model.predict(X_test)

# Evaluate the model's performance using various classification metrics
accuracy = accuracy_score(y_test, y_pred)  # Overall accuracy of predictions
precision = precision_score(y_test, y_pred, average='weighted')  # Precision score
recall = recall_score(y_test, y_pred, average='weighted')  # Recall score
f1 = f1_score(y_test, y_pred, average='weighted')  # F1 score (harmonic mean of precision and recall)
# Calculate the ROC AUC score for multi-class classification (One-vs-Rest strategy)
roc_auc = roc_auc_score(y_test, model.predict_proba(X_test), multi_class='ovr')

# Display the results
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("ROC AUC Score:", roc_auc)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0
ROC AUC Score: 1.0


### Confusion Matrix

In [ ]:
# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
